### ISSUE TITLE
CLion and PyCharm

### ISSUE THREAD

**Issue by Avamander** [Foggalong/hardcode-fixer#236] opened 2016-04-27 21:21 UTC
```
[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm
Icon=/home/<INSTALLATION DIRECTORY>/bin/pycharm.png
Exec="/home/<INSTALLATION DIRECTORY>/bin/pycharm.sh" %f
Comment=Develop with pleasure!
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-pycharm
```
```
[Desktop Entry]
Version=1.0
Type=Application
Name=CLion
Icon=/home/<INSTALLATION DIRECTORY>/bin/clion.svg
Exec="/home/<INSTALLATION DIRECTORY>/bin/clion.sh" %f
Comment=Develop with pleasure!
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-clion
```

Downloaded the version of the script available in the root directory of this repository. Neither of the icons are fixed. I do not have other JetBrains products to include more desktop entries.

**Comment by nesl247** [comment] 2016-06-26 20:27
Also have the same issue with PhpStorm. The previous examples should just be `<INSTALLATION DIRECTORY>/` instead of `/home/<INSTALLATION DIRECTORY>` though as `/home` is part of said prefix.

**Comment by Foggalong** [comment] 2016-06-27 10:24
Sorry I didn't catch this before - this is a duplicate of #149

**Closed by Foggalong** 2016-06-27 10:24 UTC
Labels: duplicate
