### ISSUE TITLE
Does not work for Intellij Idea and Visual Studio Code

### ISSUE THREAD

**Issue by krzysieki** [Foggalong/hardcode-fixer#210] opened 2015-11-30 20:56 UTC
Hi 

Thanks for your work!

Intellij Idea has hardcoded icon and this script does not solve problem.
The same with Visual Studio Code.

Please check desktop files (both located in ~/.local/share/applications):

jetbrains-idea.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=IntelliJ IDEA
Icon=/home/myname/.local/share/umake/ide/idea-ultimate/bin/idea.png
Exec="/home/myname/.local/share/umake/ide/idea-ultimate/bin/idea.sh" %f
Comment=IntelliJ IDEA (UDTC)
Categories=Development;IDE;
Terminal=false

visual-studio-code.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Visual Studio Code
Icon=/home/myname/.local/share/umake/web/visual-studio-code/resources/app/resources/linux/vscode.png
Exec=/home/myname/.local/share/umake/web/visual-studio-code/Code
Comment=Visual Studio focused on modern web and cloud
Categories=Development;IDE;
Terminal=false

**Comment by bil-elmoussaoui** [comment] 2015-12-10 20:31
See here #190

**Comment by bil-elmoussaoui** [comment] 2015-12-10 20:31
@Foggalong Duplicate of #128

**Closed** 2015-12-10 22:32 UTC
Labels: duplicate

**Comment by krzysieki** [comment] 2015-12-13 22:01
Thanks. 

I confirm that on my env #190 worked :), icons have changed, no errors occurred.
