### ISSUE TITLE
ClipGrab

### ISSUE THREAD

**Issue by tiotrom** [Foggalong/hardcode-fixer#366] opened 2020-05-22 23:33 UTC
| ClipGrab | Icon=/usr/share/pixmaps/clipgrab.png | clipgrab.desktop |

**Comment by Foggalong** [comment] 2020-09-05 12:57
Duplicate of #43

**Closed by Foggalong** 2020-09-05 12:57 UTC
Labels: duplicate

**Comment by tiotrom** [comment] 2020-09-06 13:01
For me this one does not work. I checked the paths. Everything is correct.
Icon=/usr/share/pixmaps/clipgrab.png
Yet it does not grab the clipgrab.svg icon from our icons set.
