### ISSUE TITLE
LInux Mint 17.2 clean install - broken icons after run fix.sh

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#139] opened 2015-07-07 09:50 UTC
Running fix.sh after installation of software and installation of extra software from
https://github.com/erikdubois/UltimateLinuxMint17_2

G: Fixing Hardinfo...
G: Fixing HP Printer...
G: Fixing Mint Backup...
G: Fixing Mint Backup...
G: Fixing Mint Drivers...
G: Fixing Mint Nanny...
G: Fixing Mint Software Manager...
G: Fixing Mint Software Sources...
G: Fixing Mint Update Manager...
G: Fixing Mint Upload Manager...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...
G: Fixing Variety...
Changing to Sardi Iconset. Everything has a specific icon.
Changing to Numix Circle Icon set. 
Missing icons for 
- domain blocker - > Icon points to mintNanny - NO MINTNANNY ICON IN PPA NUMIX CIRCLE
- update manager - > Icon points to mintUpdate - NO MINTNANNY ICON IN PPA NUMIX CIRCLE
- upload manager - > Icon points to mintUpload - NO MINTNANNY ICON IN PPA NUMIX CIRCLE

Checking the latest github version to find the missing icons.
- domain blocker - > on github
- update manager - > on github
- upload manager - > on github

Conclusion : Numix will have no broken icons once the current github is on PPA.

ISSUE OF BROKEN ICONS

If you stop using Sardi or Numix Circle and would like to refert back to mint-x green icons set (original icon set).

Missing icons : 
- Backup tool
- Domain Blocker
- Software Manager
- Update Manager
- Upload Manager
- Variety

Solution 1 
gtk-update-icon-cache mint-x
Tried this to see if it was solvable by updating cache
This did not solve the issue.

Solution 2

went to the folder /usr/share/icons/hicolor/48x48/apps
added the extension of .png on all missing icons and changed themes.
changed themes no change - icons still missing
did gtk-update-icon-cache mint-x  
no change
Rebooted
no change 

Solution 3 

Deleted ./home/erik/.cache/thumbnails/normal
No change

These 6 icons are still gone in Mint-x or default or gnome or all variations of mint-x

Solution 4
changed variety.png into variety.svg as I knew i made it with inkscape.
and started to move it about scalable folder. also in gnome. 
did a gtk-update-icon-cache and now it is there 
Not sure why though 
still investigating

After an other reboot all icons are there but the one of software manager is not.
Softwaremanager points to  Icon=software-properties-mint. But this image does not exist in hicolor.

Untill we are sure we can not do anything. It seems to be an caching problem...?

**Comment by bil-elmoussaoui** [comment] 2015-07-09 19:13
If i do understand the problem, is that you can't revert to the original theme as there's some missing icons? if so it's a duplicate of #129

**Closed** 2015-07-20 12:00 UTC
Labels: duplicate

**Comment by erikdubois** [comment] 2015-07-21 07:42
yes it is the same issue
and yes should you not address the situation
the solution is out there

**Comment by Foggalong** [comment] 2015-07-21 09:38
I will yes, but that doesn't mean keep opening more issues until I do :P
