### ISSUE TITLE
Icons of Jetbrains IDE installed using jetbrains toolbox not fixed

### ISSUE THREAD

**Issue by t9toqwerty** [Foggalong/hardcode-fixer#279] opened 2016-11-29 06:28 UTC
Icons are stored at .local/share/applications.
The name of shortcuts is same as ide name .
![selection_044](https://cloud.githubusercontent.com/assets/5053687/20699001/dd49bb2c-b62a-11e6-8d17-d2465851c37a.png)

Content of DataGrip IDE: 
[Desktop Entry]
Version=1.0
Type=Application
Name=DataGrip 2016.3
Icon=/opt/jetbrains/apps/datagrip/ch-0/163.7744.4/.icon.svg
Exec="/opt/jetbrains/apps/datagrip/ch-0/163.7744.4/bin/datagrip.sh" %f
Comment=Your Swiss Army knife for databases & SQL
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-datagrip

**Comment by t9toqwerty** [comment] 2016-11-29 06:29
Content of PhpStorm IDE Desktop File:

[Desktop Entry]
Version=1.0
Type=Application
Name=PhpStorm 2016.3
Icon=/opt/jetbrains/apps/PhpStorm/ch-0/163.7743.50/.icon.svg
Exec="/opt/jetbrains/apps/PhpStorm/ch-0/163.7743.50/bin/phpstorm.sh" %f
Comment=Lightning-smart PHP IDE
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-phpstorm

**Comment by bil-elmoussaoui** [comment] 2017-01-13 03:55
This is the same issue as #149. The icon name is using the version of the application, it's either we have to add too many lines for each version for each application...This can be closed as it's duplicate of the other issue ;)

**Comment by GusAndrianos** [comment] 2017-06-21 15:57
This is still not stolved. I tried running the script today but no icons have changed. This is also the case with netbeans

**Comment by Foggalong** [comment] 2017-09-04 17:18
See #149 for more info on this

**Closed by Foggalong** 2017-09-04 17:18 UTC
Labels: duplicate

**Comment by jeffshee** [comment] 2019-03-07 09:28
It seems that the version isn't being used in the icon name any more so this could be reopened for a fix. 
Example:
```
::::::::::::::
jetbrains-clion.desktop
::::::::::::::
[Desktop Entry]
Version=1.0
Type=Application
Name=CLion
Icon=/home/jeffshee/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/.icon.svg
Exec="/home/jeffshee/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/183.5429.37/
bin/clion.sh" %f
Comment=A smart cross-platform IDE for C and C++
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-clion
::::::::::::::
jetbrains-idea-ce.desktop
::::::::::::::
[Desktop Entry]
Version=1.0
Type=Application
Name=IntelliJ IDEA Community
Icon=/home/jeffshee/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/.icon.svg
Exec="/home/jeffshee/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/183.5912.21/bin/idea.sh" %f
Comment=Capable and ergonomic Java IDE
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-idea-ce
::::::::::::::
jetbrains-pycharm-ce.desktop
::::::::::::::
[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm Community
Icon=/home/jeffshee/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/.icon.svg
Exec="/home/jeffshee/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/183.5912.18/bin/pycharm.sh" %f
Comment=Python IDE for professional developers
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-pycharm-ce
::::::::::::::
jetbrains-studio.desktop
::::::::::::::
[Desktop Entry]
Version=1.0
Type=Application
Name=Android Studio
Icon=/home/jeffshee/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/.icon.svg
Exec="/home/jeffshee/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/bin/studio.sh" %f
Comment=Everything you need to build on Android
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-studio
::::::::::::::
jetbrains-toolbox.desktop
::::::::::::::
[Desktop Entry]
Type=Application
Name=JetBrains Toolbox
Exec=/home/jeffshee/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox %u
Icon=/home/jeffshee/.local/share/JetBrains/Toolbox/toolbox.svg
StartupNotify=false
Categories=Development;IDE;
Terminal=false
X-GNOME-Autostart-Delay=10
X-MATE-Autostart-Delay=10
X-KDE-autostart-after=panel
X-GNOME-Autostart-enabled=true
StartupWMClass=jetbrains-toolbox
MimeType=x-scheme-handler/jetbrains;
::::::::::::::
jetbrains-webstorm.desktop
::::::::::::::
[Desktop Entry]
Version=1.0
Type=Application
Name=WebStorm
Icon=/home/jeffshee/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/.icon.svg
Exec="/home/jeffshee/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/183.5912.23/bin/webstorm.sh" %f
Comment=The smartest JavaScript IDE
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-webstorm
```

**Comment by Foggalong** [comment] 2019-03-07 13:11
@jeffshee That'd be a new issue because it's a new entry in the db. Looking at your paste it looks more to do with where the software was installed than a packaging fix.

**Comment by philwon** [comment] 2019-11-29 17:28
I found that the line 207 of fix.sh cause this problem.  
grep -Gq should not be used here to locate the path of the hardcode icon. It won't work as expected.
